generator68k: fix parallel build
fixes dependency chain for generated headers:

Making all in generator68k
make[3]: Entering directory `/home/rofl/tmp/gngeo/src/generator68k'
gcc -c def68k.c -o def68k.o -I .. -I ../.. -I . `sdl2-config --cflags` -Umain -Dmain=main
gcc -c tab68k2.c -o tab68k2.o -I .. -I ../.. -I . `sdl2-config --cflags` -Umain -Dmain=main
gcc -c gen68k.c -o gen68k.o -I .. -I ../.. -I . `sdl2-config --cflags` -Umain -Dmain=main
gen68k.c:8:25: fatal error: def68k-iibs.h: No such file or directory
 #include "def68k-iibs.h"
                         ^
also use a stamp file for files generated by gen68k so it isn't invoked
once per generated source file, with each process overwriting each others
output.

remake -x output:
          Prerequisite `gen68k' is newer than target `cpu68k-0.c'.
          /tmp/gngeo/src/generator68k/Makefile:663      Must remake target `cpu68k-0.c'.
Invoking recipe from Makefile:664 to update target `cpu68k-0.c'.
 ##>>>>>>>>>>>>>>>>>>>>>>>>>>0>>>>>>>>>>>>>>>>>>>>>>>>>>>>
./gen68k 2>&1 >/dev/null
 ##<<<<<<<<<<<<<<<<<<<<<<<<<<0<<<<<<<<<<<<<<<<<<<<<<<<<<<<
        /tmp/gngeo/src/generator68k/Makefile:666        File `cpu68k-1.o' does not exist.
          Prerequisite `gen68k' is newer than target `cpu68k-1.c'.
          /tmp/gngeo/src/generator68k/Makefile:663      Must remake target `cpu68k-1.c'.
Invoking recipe from Makefile:664 to update target `cpu68k-1.c'.
 ##>>>>>>>>>>>>>>>>>>>>>>>>>>0>>>>>>>>>>>>>>>>>>>>>>>>>>>>
./gen68k 2>&1 >/dev/null